// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:convert' as _i31;
import 'dart:typed_data' as _i32;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ditonton/common/failure.dart' as _i10;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i18;
import 'package:ditonton/data/datasources/db/tv_series_database.dart' as _i4;
import 'package:ditonton/data/datasources/db/tv_series_database_helper.dart'
    as _i20;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i15;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i13;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i30;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i28;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i3;
import 'package:ditonton/data/models/movie_model.dart' as _i14;
import 'package:ditonton/data/models/movie_table.dart' as _i16;
import 'package:ditonton/data/models/tv_episode_table.dart' as _i24;
import 'package:ditonton/data/models/tv_season_detail_response.dart' as _i6;
import 'package:ditonton/data/models/tv_season_table.dart' as _i23;
import 'package:ditonton/data/models/tv_series_detail_response.dart' as _i5;
import 'package:ditonton/data/models/tv_series_response.dart' as _i29;
import 'package:ditonton/data/models/tv_series_table.dart' as _i22;
import 'package:ditonton/domain/entities/movie.dart' as _i11;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i12;
import 'package:ditonton/domain/entities/tv_season.dart' as _i27;
import 'package:ditonton/domain/entities/tv_series.dart' as _i26;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i21;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i8;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i25;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:sqflite/sqflite.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieDetailResponse_1 extends _i1.SmartFake
    implements _i3.MovieDetailResponse {
  _FakeMovieDetailResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDatabase_2 extends _i1.SmartFake
    implements _i4.TvSeriesDatabase {
  _FakeTvSeriesDatabase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeriesDetailResponse_3 extends _i1.SmartFake
    implements _i5.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTvSeasonDetailResponse_4 extends _i1.SmartFake
    implements _i6.TvSeasonDetailResponse {
  _FakeTvSeasonDetailResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_5 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_6 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i8.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
            Invocation.method(
              #getNowPlayingMovies,
              [],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
              this,
              Invocation.method(
                #getNowPlayingMovies,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #getTopRatedMovies,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>>.value(
                _FakeEither_0<_i10.Failure, _i12.MovieDetail>(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i12.MovieDetail>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getMovieRecommendations,
              [id],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
              this,
              Invocation.method(
                #getMovieRecommendations,
                [id],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #searchMovies,
            [query],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveWatchlist(
          _i12.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [movie],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeWatchlist(
          _i12.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>.value(
                _FakeEither_0<_i10.Failure, List<_i11.Movie>>(
          this,
          Invocation.method(
            #getWatchlistMovies,
            [],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i11.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i13.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i14.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNowPlayingMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTopRatedMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetail,
          [id],
        ),
        returnValue: _i9.Future<_i3.MovieDetailResponse>.value(
            _FakeMovieDetailResponse_1(
          this,
          Invocation.method(
            #getMovieDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.MovieDetailResponse>);

  @override
  _i9.Future<List<_i14.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieRecommendations,
          [id],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);

  @override
  _i9.Future<List<_i14.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovies,
          [query],
        ),
        returnValue:
            _i9.Future<List<_i14.MovieModel>>.value(<_i14.MovieModel>[]),
      ) as _i9.Future<List<_i14.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i15.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [movie],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> removeWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [movie],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i16.MovieTable?> getMovieById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i9.Future<_i16.MovieTable?>.value(),
      ) as _i9.Future<_i16.MovieTable?>);

  @override
  _i9.Future<List<_i16.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue:
            _i9.Future<List<_i16.MovieTable>>.value(<_i16.MovieTable>[]),
      ) as _i9.Future<List<_i16.MovieTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i18.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i19.Database?> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i9.Future<_i19.Database?>.value(),
      ) as _i9.Future<_i19.Database?>);

  @override
  _i9.Future<int> insertWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<int> removeWatchlist(_i16.MovieTable? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [movie],
        ),
        returnValue: _i9.Future<int>.value(0),
      ) as _i9.Future<int>);

  @override
  _i9.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieById,
          [id],
        ),
        returnValue: _i9.Future<Map<String, dynamic>?>.value(),
      ) as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistMovies,
          [],
        ),
        returnValue: _i9.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i9.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [TvSeriesDatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesDatabaseHelper extends _i1.Mock
    implements _i20.TvSeriesDatabaseHelper {
  MockTvSeriesDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i4.TvSeriesDatabase> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue:
            _i9.Future<_i4.TvSeriesDatabase>.value(_FakeTvSeriesDatabase_2(
          this,
          Invocation.getter(#database),
        )),
      ) as _i9.Future<_i4.TvSeriesDatabase>);

  @override
  _i9.Future<void> insertTvSeriesWatchlist(_i21.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertTvSeriesWatchlist,
          [tvSeries],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> removeTvSeriesWatchlist(int? tvSeriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeTvSeriesWatchlist,
          [tvSeriesId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i22.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [id],
        ),
        returnValue: _i9.Future<_i22.TvSeriesTable?>.value(),
      ) as _i9.Future<_i22.TvSeriesTable?>);

  @override
  _i9.Future<List<_i23.TvSeasonTable>> getSeasonsByTvSeriesId(
          int? tvSeriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonsByTvSeriesId,
          [tvSeriesId],
        ),
        returnValue:
            _i9.Future<List<_i23.TvSeasonTable>>.value(<_i23.TvSeasonTable>[]),
      ) as _i9.Future<List<_i23.TvSeasonTable>>);

  @override
  _i9.Future<_i23.TvSeasonTable?> getSeasonDetail(
    int? tvSeriesId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [
            tvSeriesId,
            seasonNumber,
          ],
        ),
        returnValue: _i9.Future<_i23.TvSeasonTable?>.value(),
      ) as _i9.Future<_i23.TvSeasonTable?>);

  @override
  _i9.Future<List<_i24.TvEpisodeTable>> getEpisodesBySeasonId(int? seasonId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesBySeasonId,
          [seasonId],
        ),
        returnValue: _i9.Future<List<_i24.TvEpisodeTable>>.value(
            <_i24.TvEpisodeTable>[]),
      ) as _i9.Future<List<_i24.TvEpisodeTable>>);

  @override
  _i9.Future<List<_i22.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i9.Future<List<_i22.TvSeriesTable>>.value(<_i22.TvSeriesTable>[]),
      ) as _i9.Future<List<_i22.TvSeriesTable>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i25.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>
      getAiringTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getAiringTvSeries,
              [],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
              this,
              Invocation.method(
                #getAiringTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getPopularTvSeries,
              [],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
              this,
              Invocation.method(
                #getPopularTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getTopRatedTvSeries,
              [],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
              this,
              Invocation.method(
                #getTopRatedTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i21.TvSeriesDetail>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, _i21.TvSeriesDetail>>.value(
                _FakeEither_0<_i10.Failure, _i21.TvSeriesDetail>(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i21.TvSeriesDetail>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, _i27.TvSeason>> getSeasonDetail(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [
            tvId,
            seasonNumber,
          ],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, _i27.TvSeason>>.value(
            _FakeEither_0<_i10.Failure, _i27.TvSeason>(
          this,
          Invocation.method(
            #getSeasonDetail,
            [
              tvId,
              seasonNumber,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, _i27.TvSeason>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
            Invocation.method(
              #getTvSeriesRecommendations,
              [id],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
              this,
              Invocation.method(
                #getTvSeriesRecommendations,
                [id],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>> searchTvSeries(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [query],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
          this,
          Invocation.method(
            #searchTvSeries,
            [query],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> saveWatchlist(
          _i21.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWatchlist,
          [tvSeries],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #saveWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, String>> removeWatchlist(
          int? tvSeriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tvSeriesId],
        ),
        returnValue: _i9.Future<_i2.Either<_i10.Failure, String>>.value(
            _FakeEither_0<_i10.Failure, String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tvSeriesId],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i10.Failure, String>>);

  @override
  _i9.Future<bool> isAddedToWatchlist(int? id) => (super.noSuchMethod(
        Invocation.method(
          #isAddedToWatchlist,
          [id],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
            Invocation.method(
              #getWatchlistTvSeries,
              [],
            ),
            returnValue:
                _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>.value(
                    _FakeEither_0<_i10.Failure, List<_i26.TvSeries>>(
              this,
              Invocation.method(
                #getWatchlistTvSeries,
                [],
              ),
            )),
          ) as _i9.Future<_i2.Either<_i10.Failure, List<_i26.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i28.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i29.TvSeriesResponse>> getAiringTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiringTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i29.TvSeriesResponse>>.value(
            <_i29.TvSeriesResponse>[]),
      ) as _i9.Future<List<_i29.TvSeriesResponse>>);

  @override
  _i9.Future<List<_i29.TvSeriesResponse>> getPopularTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i29.TvSeriesResponse>>.value(
            <_i29.TvSeriesResponse>[]),
      ) as _i9.Future<List<_i29.TvSeriesResponse>>);

  @override
  _i9.Future<List<_i29.TvSeriesResponse>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopRatedTvSeries,
          [],
        ),
        returnValue: _i9.Future<List<_i29.TvSeriesResponse>>.value(
            <_i29.TvSeriesResponse>[]),
      ) as _i9.Future<List<_i29.TvSeriesResponse>>);

  @override
  _i9.Future<_i5.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesDetail,
          [id],
        ),
        returnValue: _i9.Future<_i5.TvSeriesDetailResponse>.value(
            _FakeTvSeriesDetailResponse_3(
          this,
          Invocation.method(
            #getTvSeriesDetail,
            [id],
          ),
        )),
      ) as _i9.Future<_i5.TvSeriesDetailResponse>);

  @override
  _i9.Future<_i6.TvSeasonDetailResponse> getSeasonDetail(
    int? tvId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [
            tvId,
            seasonNumber,
          ],
        ),
        returnValue: _i9.Future<_i6.TvSeasonDetailResponse>.value(
            _FakeTvSeasonDetailResponse_4(
          this,
          Invocation.method(
            #getSeasonDetail,
            [
              tvId,
              seasonNumber,
            ],
          ),
        )),
      ) as _i9.Future<_i6.TvSeasonDetailResponse>);

  @override
  _i9.Future<List<_i29.TvSeriesResponse>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesRecommendations,
          [id],
        ),
        returnValue: _i9.Future<List<_i29.TvSeriesResponse>>.value(
            <_i29.TvSeriesResponse>[]),
      ) as _i9.Future<List<_i29.TvSeriesResponse>>);

  @override
  _i9.Future<List<_i29.TvSeriesResponse>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTvSeries,
          [query],
        ),
        returnValue: _i9.Future<List<_i29.TvSeriesResponse>>.value(
            <_i29.TvSeriesResponse>[]),
      ) as _i9.Future<List<_i29.TvSeriesResponse>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i30.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i21.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWatchlist,
          [tvSeries],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #insertWatchlist,
            [tvSeries],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<String> removeWatchlist(int? tvSeriesId) => (super.noSuchMethod(
        Invocation.method(
          #removeWatchlist,
          [tvSeriesId],
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #removeWatchlist,
            [tvSeriesId],
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i22.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeriesById,
          [id],
        ),
        returnValue: _i9.Future<_i22.TvSeriesTable?>.value(),
      ) as _i9.Future<_i22.TvSeriesTable?>);

  @override
  _i9.Future<List<_i23.TvSeasonTable>> getSeasonsByTvSeriesId(
          int? tvSeriesId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonsByTvSeriesId,
          [tvSeriesId],
        ),
        returnValue:
            _i9.Future<List<_i23.TvSeasonTable>>.value(<_i23.TvSeasonTable>[]),
      ) as _i9.Future<List<_i23.TvSeasonTable>>);

  @override
  _i9.Future<_i23.TvSeasonTable?> getSeasonDetail(
    int? tvSeriesId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonDetail,
          [
            tvSeriesId,
            seasonNumber,
          ],
        ),
        returnValue: _i9.Future<_i23.TvSeasonTable?>.value(),
      ) as _i9.Future<_i23.TvSeasonTable?>);

  @override
  _i9.Future<List<_i22.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchlistTvSeries,
          [],
        ),
        returnValue:
            _i9.Future<List<_i22.TvSeriesTable>>.value(<_i22.TvSeriesTable>[]),
      ) as _i9.Future<List<_i22.TvSeriesTable>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i7.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i31.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i31.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i31.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i31.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i9.Future<_i7.Response>.value(_FakeResponse_5(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response>);

  @override
  _i9.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<String>.value(_i17.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i9.Future<String>);

  @override
  _i9.Future<_i32.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i9.Future<_i32.Uint8List>.value(_i32.Uint8List(0)),
      ) as _i9.Future<_i32.Uint8List>);

  @override
  _i9.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i9.Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_6(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i9.Future<_i7.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
